### ISSUE TITLE
Rule `no-internal-module` is already handled by prettier

### ISSUE THREAD

**Issue by xcatliu** [prettier/tslint-config-prettier#234]
Prettier will replace

```ts
module Foo {}
```

to

```ts
namespace Foo {}
```

So it's fine to disable [`no-internal-module`](https://palantir.github.io/tslint/rules/no-internal-module/) in tslint-config-prettier

![image](https://user-images.githubusercontent.com/5453359/48933505-7c297200-ef3b-11e8-8385-d2cd51fdc59c.png)

**Comment by ikatyang** [comment]
Good catch! We should fix it in Prettier, tracked in prettier/prettier#5533.
