### ISSUE TITLE
Vue SFC reporting <template> block as white space

### ISSUE THREAD

**Issue by danielwaltz** [prettier/tslint-config-prettier#259]
I'm using this with Vue single file components and I'm running into an issue where the linter is reporting the entire `<template>` block as white space that needs to be removed.

I have pushed up a [repo](https://github.com/danielwaltz/vue-typescript-prettier) with a starter project that replicates this issue. Just clone that somewhere, run `yarn && yarn lint` and you can see the output from prettier tells you to delete white space.

**Comment by ikatyang** [comment]
Hi, it looks like `@vue/cli-plugin-typescript` replaces non-script parts with whitespaces before passing into `tslint`, there's nothing we can do on the `tslint-config-prettier`/`tslint-plugin-prettier` side. This issue should be moved to [`vuejs/vue-cli`](https://github.com/vuejs/vue-cli).
