### ISSUE TITLE
Conflict rules

### ISSUE THREAD

**Issue by Webbrother** [prettier/tslint-config-prettier#281]
According to description of CLI i use `tslint-config-prettier-check ./tslint.json` to detect conflict rules.

And I found that there is one conflict rule `newline-per-chained-call`.

1. So what should I do now with this conflict?
2. I need so `newline-per-chained-call` to be `true`, but seems I can not extend rules with my own value of `newline-per-chained-call` rule.
So what should I do with this rule? How should I extend it?
Why I just can not extend tslint.json config with my own rules?

**Comment by ikatyang** [comment]
1. You should turn it off.
2. It's conflict with Prettier's output so there's no way to use it with Prettier at the same time.
