### ISSUE TITLE
`jsx-wrap-multiline` from `tslint-react` should be turned off

### ISSUE THREAD

**Issue by DeX3** [prettier/tslint-config-prettier#300]
Prettier does not wrap multiline-jsx in parens when it is the argument to a function, but the `jsx-wrap-multiline` rule expects parens around EVERY multiline-jsx expression.

For example:

```ts
    renderApp(
        <Providers
            apolloClient={apolloClient}
            locale={locale}
            messages={messages}
            renderRouter={renderRouter}
        />,
        document.getElementById('root'),
    );
```

This is exactly how prettier would format the code with default settings, but it will make the `jsx-wrap-multiline` rule fail, because it expects:

```ts
    renderApp(
        (<Providers
            apolloClient={apolloClient}
            locale={locale}
            messages={messages}
            renderRouter={renderRouter}
        />),
        document.getElementById('root'),
    );
```

**Comment by ikatyang** [comment]
It's [already disabled](https://github.com/prettier/tslint-config-prettier/tree/master/src/tslint-react/jsx-wrap-multiline). I guess you did not [extend it correctly](https://github.com/prettier/tslint-config-prettier#get-started) or the way you enabled that rule takes precedence over the `extends` field, see https://github.com/prettier/tslint-config-prettier/issues/280#issuecomment-468116804 for more info.

**Comment by DeX3** [comment]
Yep you were right, just in case someone runs into the same issue, the problem was, that we were using a base-tslint.json that had `"extends": ["tslint:recommended", "tslint-config-prettier"]` and we extended THAT config with `"extends": ["../../tslint.json", "tslint-react"]`, which caused `tslint-react` to overrule `tslint-config-prettier` again.

Had to re-add `tslint-config-prettier` also to our extended config to make it work.
