### ISSUE TITLE
Need a way to specify a path to prettier config file

### ISSUE THREAD

**Issue by EJMason** [prettier/tslint-config-prettier#330]
Some of my projects do not keep my .prettierrc at the root of the project. Is there any way to specify to tslint-config-prettier where to look for the prettier config file location?

**Comment by ikatyang** [comment]
`tslint-config-prettier` only turns off the conflict rules. Are you looking for [`tslint-plugin-prettier` options](https://github.com/prettier/tslint-plugin-prettier#options)?

**Comment by ikatyang** [comment]
Closed due to inactivity.
