### ISSUE TITLE
What does it mean by `Make sure you've already set up TSLint and Prettier`?

### ISSUE THREAD

**Issue by elgs** [prettier/tslint-config-prettier#343]
In the README.md, you mentioned:

> Make sure you've already set up TSLint and Prettier.

Does it mean:
1. `tslint` and `prettier` need to be `export`ed in the `PATH`? or,
2. they need to be installed in the node_modules?

Thanks.

**Comment by ikatyang** [comment]
2\. They should be installed in the `node_modules`.
