### ISSUE TITLE
tslint rules don't overvrite pritter settings

### ISSUE THREAD

**Issue by ppsirius** [prettier/tslint-config-prettier#425]
I setup newest version of tslint-config-prettier in tslint.json. In vscode I have instaled prettier with settings   `"editor.formatOnSave": true` but after save I get " instead of '. So somethings wrong, I should put something more in settings to load tsconfig to prettier?

**Comment by itibbers** [comment]
I have the same issue. It's not working.

**Comment by ppsirius** [comment]
I saw that tslint is deprecated so try to move to eslint (in pain) 😞

**Comment by ikatyang** [comment]
It sounds like you're using the Prettier VSCode extension instead of using TSLint directly, please refer to the [Linter Integration](https://github.com/prettier/prettier-vscode#linter-integration) section in the Prettier VSCode extension docs.
